### ISSUE TITLE
Support ECOS

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/diffcp#31]
It'd be great if diffcp supported the [ECOS solver](https://web.stanford.edu/~boyd/papers/pdf/ecos_ecc.pdf).

ECOS also uses a self-dual homogeneous embedding for cone programs. The details might be slightly different.

**Comment by bungun** [comment]
I’d suggest we talk to Santiago Akle since he’s very familiar w/the solver and has thoughts on obvious improvements afaik

On Dec 24, 2019, at 20:21, Akshay Agrawal <notifications@github.com> wrote:

﻿

It'd be great if diffcp supported the ECOS solver<https://web.stanford.edu/~boyd/papers/pdf/ecos_ecc.pdf>.

ECOS also uses a self-dual homogeneous embedding for cone programs. The details might be slightly different.

**Comment by rileyjmurray** [comment]
It looks like if a given solver's optimal primal-dual solution can be mapped into SCS format, then differentiation should be straightforward. Specifically, I think this would basically amount to removing [these lines](https://github.com/cvxgrp/diffcp/blob/b3176024a4517a91becd3381012c41007a4a1e53/diffcp/cone_program.py#L248-L270) from a version of ``solve_and_derivative_internal``, and requiring optimal "warm-started" values for ``x, s, y``.

@akshayka does that sound accurate? If so, then we could just look expanding cvxpy with some reductions that transform other solvers' solutions into SCS format. I'd be happy to take a stab at the MOSEK --> SCS reduction, if you're open to this approach.

**Comment by akshayka** [comment]
Riley, that sounds about right. A MOSEK to SCS reduction would be very
useful! It’d be awesome if we could differentiate through other solvers in
CVXPY.

**Comment by yanshen0** [comment]
Just curious, will MOSEK be supported any time soon? Thanks!

**Comment by JochenC** [comment]
I would be keen to use MOSEK with cvxpylayers, too.

**Comment by rileyjmurray** [comment]
From the discussion above, the best thing to do is create a reduction that transforms a MOSEK solution into the standard form used by SCS/ECOS. I thought I would have time to do that, but it didn't pan out. Taking it from here shouldn't be that hard since we already have the "dualize" reduction in place. Someone could create a GitHub issue on the CVXPY repository for making the MOSEK --> SCS reduction.

**Comment by hudson-ai** [comment]
Bumping. Also wondering if there has been any progress in adding MOSEK support in diffcp!
